### ISSUE TITLE
systemd service file generation corrupted for jinja2 templater

### ISSUE THREAD

**Issue by milouse** [9seconds/concierge#15]
### Step to reproduce

Enter the following command:

```bash
concierge -u jinja --systemd --curlsh
```
### Expected result

We should get the following working service file:

```
[Unit]
Description=Daemon for converting ~/.concierge to ~/.ssh/config

[Service]
ExecStart=/usr/bin/concierge -u jinja -o /home/etienne/.ssh/config
Restart=on-failure

[Install]
WantedBy=default.target
```
### Actual result

```
[Unit]
Description=Daemon for converting ~/.concierge to ~/.ssh/config

[Service]
ExecStart=/usr/bin/concierge -u jinja2 -o /home/etienne/.ssh/config
Restart=on-failure

[Install]
WantedBy=default.target
```
Note the **jinja2** params instead of jinja.

### Note

I have no time for now to check this one. But it leverages for me a question: what is the intended behavior? Must the templater be called with `jinja2` or just `jinja` ? `jinja` is the only param understood by the cli interface for now and map toward jinja2, but it may be the real bug.

**Comment by 9seconds** [comment]
Intended behavior is to use just 'jinja' as CLI says. Internal mechanics is based on [setuptools entrypoints](http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) and since Jinja2 plugin entrypoint is `jinja` so there should be no `jinja2` string anywhere.
